# make  to compile without debug info
# make DEBUG=1 to compile with debug info
all: H.BIN HBL.prx

CC = psp-gcc

# use a different FOLDER to make for different exploits
# Exploit-specific files go in the subfolders, see targets hbl and loader below
FLAGS = FOLDER=$(FOLDER)

ifdef NID_DEBUG
FLAGS += NID_DEBUG=$(NID_DEBUG)
endif

ifdef DEBUG
CFLAGS += DEBUG=$(DEBUG)
endif

H.BIN: svnversion.h libpspuser/libpspuser.a
	make -f Makefile_h $(FLAGS)

HBL.prx: svnversion.h libpspuser/libpspuser.a
	make -f Makefile_hbl $(FLAGS)

#svn version in code
svnversion.h:
	-@echo "//svnversion.h is automatically generated by the Makefile!!!" > svnversion.h
	-@echo "" >> svnversion.h
	-@echo "#ifndef SVNVERSION" >> svnversion.h
	-@echo "#define SVNVERSION \"$(shell svnversion -n)\"" >> svnversion.h
	-@echo "#endif" >> svnversion.h
	-SubWCRev . svnversion.txt svnversion.h

libpspuser/libpspuser.a:
	make -C libpspuser -f Makefile

clean:
	rm -f svnversion.h
	make -C libpspuser -f Makefile clean
	make -f Makefile_h clean
	make -f Makefile_hbl clean
