/* This file was automatically generated by eLoaderconf.rb */
#ifndef ELOADER_LOADER
#define ELOADER_LOADER

// HBL stubs size
#define NUM_HBL_IMPORTS 0x40
// HBL stubs address
#define HBL_STUBS_START 0x10000
#define GLOBALS_ADDR 0x10200
#define GLOBALS_END_ADDR 0x14000

#endif
