/* This file was automatically generated by eLoaderconf.rb */
#ifndef ELOADER_LOADER
#define ELOADER_LOADER

// HBL stubs size
#define NUM_HBL_IMPORTS 0x3d
// HBL stubs address
#define HBL_STUBS_START 0x10000

#endif
